---
title: "Exploratory Analysis: Air Pollution"
author: "Robert A. Giaquinto"
date: "May 26, 2015"
output: html_document
---

# Load Data
```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(Hmisc)
library(ggplot2)
library(scales)
library(reshape2)
library(dplyr)
library(xtable)
library(lubridate)
```

```{r, results='asis'}
data_dir='/Users/robert/Documents/UMN/air_pollution/'
DF <- read.csv(paste0(data_dir, 'all_data.csv'), stringsAsFactors=FALSE)
DF$Date <- ymd(DF$Date_Local)
DF$Date_Local <- NULL
DF$Year <- year(DF$Date)
DF$Longitude <- as.numeric(DF$Longitude)
DF$Latitude <- as.numeric(DF$Latitude)

by_state <- DF %>%
    group_by(State_Code) %>%
    summarize(avg=mean(pm25),
        stdev=sd(pm25),
        num=length(pm25))
by_state <- by_state[order(by_state$num),]
print(xtable(by_state, type='html'))

```


Describe the data:

```{r}
describe(DF)
```

map locations:

```{r}
library(ggmap)
map <- get_map(location = 'united states', zoom=4, color="bw")
p <- ggmap(map)
agg_df <- DF %>%
    group_by(Latitude, Longitude) %>%
    summarise(ct = length(pm25))
map_df <- as.data.frame(agg_df[agg_df$ct > 20000 &
        agg_df$Latitude > 20 &
        agg_df$Latitude < 55 &
        agg_df$Longitude > -130 &
        agg_df$Longitude < 60,])
p + geom_point(data=map_df, aes(x=Longitude, y=Latitude), color="red")


```

cluster locations

```{r,results='asis'}
n_clusters <- 8
X <- as.matrix(map_df[,1:2])

#  K-Means clustering, scale the data matrix.
clusters <- kmeans(scale(X), n_clusters, iter.max = 25)

#  Add cluster label to the data frame.
map_df$cluster <- factor(clusters$cluster)

#  Examine the cluster averages (use unlogged, unscaled variable values).
centers <- map_df %>% group_by(cluster) %>%
    summarise(Latitude = mean(Latitude),
        Longitude = mean(Longitude),
        num_unique = length(ct),
        num = sum(ct))
centers <- centers[order(centers$num, decreasing=TRUE),]
print(xtable(centers), type='html')

```

plot clusters
```{r}
biggest_clusters <- map_df[map_df$cluster %in% centers$cluster[1:n_clusters],]
p + geom_point(data=biggest_clusters, aes(x=Longitude, y=Latitude, colour=cluster), size=3) +
    theme(legend.position = "none")

p + geom_hex(data=biggest_clusters, aes(x=Longitude, y=Latitude, fill=cluster),
        colour = "white", alpha = .6) +
    geom_point(data = centers,
        aes(x = Longitude,
            y = Latitude),
        colour = "black",
        alpha=.6,
        size = 16) +
    geom_point(data = centers,
        aes(x = Longitude,
            y = Latitude,
            colour = cluster),
        alpha=.6,
        size = 15) +
    geom_text(data = centers,
        aes(x = Longitude,
            y = Latitude,
            label = paste0(cluster, "~", num_unique)),
        size=4,
        colour = "black") +
    labs(title = "Spatial Clusters") +
    theme(legend.position = "none")

```

zoom in on cluster in north west:

```{r}
washington <- get_map(location = c(lon=-119.8554, lat=45.82009), zoom=6, color="bw")
p <- ggmap(washington)
biggest_cluster <- map_df[map_df$cluster %in% centers$cluster[1],]
p + geom_point(data=biggest_cluster, aes(x=Longitude, y=Latitude), color="red")

```
